# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datum.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x64\x61tum.proto\"*\n\x0bSimpleDatum\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\x12\r\n\x05label\x18\x02 \x01(\x0c\"\x87\x01\n\x03Utt\x12\x14\n\x0c\x66rame_length\x18\x01 \x01(\x05\x12\x13\n\x0b\x66\x65\x61ture_dim\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x12\n\nstate_data\x18\x04 \x01(\x0c\x12\x0f\n\x07\x65\x64_data\x18\x05 \x01(\x0c\x12\x0f\n\x07word_id\x18\x06 \x01(\x05\x12\x11\n\twave_name\x18\x07 \x02(\x0c\" \n\x0bSpeechDatum\x12\x11\n\x03\x61nc\x18\x01 \x01(\x0b\x32\x04.Utt')
)




_SIMPLEDATUM = _descriptor.Descriptor(
  name='SimpleDatum',
  full_name='SimpleDatum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SimpleDatum.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='SimpleDatum.label', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=57,
)


_UTT = _descriptor.Descriptor(
  name='Utt',
  full_name='Utt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_length', full_name='Utt.frame_length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_dim', full_name='Utt.feature_dim', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Utt.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_data', full_name='Utt.state_data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ed_data', full_name='Utt.ed_data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='word_id', full_name='Utt.word_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wave_name', full_name='Utt.wave_name', index=6,
      number=7, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=195,
)


_SPEECHDATUM = _descriptor.Descriptor(
  name='SpeechDatum',
  full_name='SpeechDatum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='anc', full_name='SpeechDatum.anc', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=229,
)

_SPEECHDATUM.fields_by_name['anc'].message_type = _UTT
DESCRIPTOR.message_types_by_name['SimpleDatum'] = _SIMPLEDATUM
DESCRIPTOR.message_types_by_name['Utt'] = _UTT
DESCRIPTOR.message_types_by_name['SpeechDatum'] = _SPEECHDATUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleDatum = _reflection.GeneratedProtocolMessageType('SimpleDatum', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEDATUM,
  __module__ = 'datum_pb2'
  # @@protoc_insertion_point(class_scope:SimpleDatum)
  ))
_sym_db.RegisterMessage(SimpleDatum)

Utt = _reflection.GeneratedProtocolMessageType('Utt', (_message.Message,), dict(
  DESCRIPTOR = _UTT,
  __module__ = 'datum_pb2'
  # @@protoc_insertion_point(class_scope:Utt)
  ))
_sym_db.RegisterMessage(Utt)

SpeechDatum = _reflection.GeneratedProtocolMessageType('SpeechDatum', (_message.Message,), dict(
  DESCRIPTOR = _SPEECHDATUM,
  __module__ = 'datum_pb2'
  # @@protoc_insertion_point(class_scope:SpeechDatum)
  ))
_sym_db.RegisterMessage(SpeechDatum)


# @@protoc_insertion_point(module_scope)
